name: Lint Check

on:
  pull_request:
    branches:
      - main  # Ou outra branch principal do projeto

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Executar ESLint
        run: npm run lint
